In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/content/drive/My Drive/CSV files for Deep learning and ML/Fake news/train.csv")

In [3]:
data.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [4]:
data.shape

(20800, 5)

In [5]:
data.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [6]:
# Dropping all the rows with null values

data = data.dropna()

In [7]:
# Get the independent features

X = data.drop("label", axis = 1)

In [8]:
# Get the dependent feature

y = data["label"]

In [9]:
#Check if the data is imbalanced.

y.value_counts()

0    10361
1     7924
Name: label, dtype: int64

- Here we see that there are 10,000 labels for 0 and 8000 labels for 1. Hence the data is not imbalanced. Hence we can use Accuracy Score as our evaluation metrics.

In [10]:
X.shape

(18285, 4)

In [11]:
y.shape

(18285,)

In [12]:
import tensorflow as tf

In [13]:
tf.__version__

'2.2.0'

In [14]:
from tensorflow.keras.layers import Embedding # Used to convert the sentence to vectors
from tensorflow.keras.preprocessing.sequence import pad_sequences # to make all sentences of equal size
from tensorflow.keras.preprocessing.text import one_hot # To convert words to numerical form
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dense

In [15]:
## Vocabulary size (when we are implementing One-Hot representation we need a dictionary size within which, all the words will be given some kind of sequence)

vocab_size = 5000

## One Hot Representation

In [16]:
message = X.copy()

In [17]:
message["title"][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [18]:
message.reset_index(inplace = True)

In [19]:
import nltk
import re
from nltk.corpus import stopwords

In [20]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [21]:
# Dataset Preprocessing

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range (0, len(message)):
  print(i)
  review = re.sub("[^a-zA-Z]", " ", message["title"][i]) # remove all special characters from the title
  review = review.lower() # Converting all the words to lower case\
  review = review.split() # splitting each word

  review = [ps.stem(word) for word in review if not word in stopwords.words("english")]
  review = " ".join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
13443
1

In [22]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [23]:
# One hot encoding will assign some index to each word in the corpus

onehot_rep = [one_hot(words, vocab_size) for words in corpus]

In [24]:
onehot_rep

[[4350, 1928, 1223, 432, 4220, 3230, 3998, 780, 1623, 2717],
 [273, 1106, 3366, 4213, 3082, 3315, 4389],
 [3106, 646, 3882, 3838],
 [903, 86, 3749, 1887, 4531, 3258],
 [95, 3082, 4320, 2781, 2313, 2116, 3082, 3427, 3073, 1876],
 [583,
  2385,
  1221,
  1546,
  4835,
  83,
  3409,
  2938,
  1356,
  776,
  1652,
  3597,
  3023,
  4059,
  4389],
 [4313, 651, 4632, 4396, 740, 222, 3824, 326, 4794, 4918, 390],
 [2427, 1123, 4467, 4326, 1629, 3309, 83, 2553, 4794, 4918, 390],
 [2744, 3243, 79, 4975, 1180, 904, 480, 1021, 83, 1252],
 [3037, 1939, 170, 4373, 27, 2693, 3531, 1801],
 [1533, 4802, 2725, 4871, 4974, 1625, 275, 78, 4824, 1301, 492],
 [1887, 3246, 4220, 904, 83, 1629],
 [3350, 538, 4689, 1295, 3526, 1867, 1582, 4306, 196],
 [4968, 2236, 3165, 999, 4829, 151, 2187, 4794, 4918, 390],
 [471, 659, 4487, 1478, 1995, 4794, 4918, 390],
 [3953, 2592, 3291, 4495, 1434, 847, 1071, 1991, 3202, 500],
 [2576, 2659, 1106],
 [4959, 3127, 367, 3941, 83, 1790, 1918, 4389],
 [1894, 2390, 3366, 3962, 

## Embedding Representation

- This is done to make all the sentences of the same size

In [25]:
sent_length = 25
embedded_doc = pad_sequences(onehot_rep, padding = "pre", maxlen = sent_length)
print(embedded_doc)

[[   0    0    0 ...  780 1623 2717]
 [   0    0    0 ... 3082 3315 4389]
 [   0    0    0 ...  646 3882 3838]
 ...
 [   0    0    0 ... 4794 4918  390]
 [   0    0    0 ...  661 1945  400]
 [   0    0    0 ... 1941  495 2086]]


In [26]:
embedded_doc[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0, 4350, 1928, 1223,  432, 4220, 3230, 3998,
        780, 1623, 2717], dtype=int32)

## Creating The Model

In [27]:
embedding_vector_features = 40 # each sentence in embedding_doc will be represented in 40 dimensions while embedding it to vectors
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_features, input_length=sent_length)) # embedding is used to convert the numerical values in embedded_doc to vector
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1, activation = "sigmoid"))
model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 25, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


- When we use bidirectional LSTM, that time, two LSTM are created, one in forward direction and one in backward direction.

In [28]:
import numpy as np
X_final = np.array(embedded_doc)
y_final = np.array(y)

In [29]:
X_final.shape, y_final.shape

((18285, 25), (18285,))

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.25, random_state = 42)

## Model Training

In [42]:
model.fit(X_train, y_train, validation_data =(X_test, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
215/215 [==============================] - 12s 55ms/step - loss: 0.0078 - accuracy: 0.9977 - val_loss: 0.5578 - val_accuracy: 0.9092
Epoch 2/10
215/215 [==============================] - 12s 55ms/step - loss: 0.0103 - accuracy: 0.9969 - val_loss: 0.5627 - val_accuracy: 0.9020
Epoch 3/10
215/215 [==============================] - 12s 55ms/step - loss: 0.0063 - accuracy: 0.9982 - val_loss: 0.6114 - val_accuracy: 0.9077
Epoch 4/10
215/215 [==============================] - 12s 56ms/step - loss: 0.0042 - accuracy: 0.9986 - val_loss: 0.6843 - val_accuracy: 0.9027
Epoch 5/10
215/215 [==============================] - 12s 56ms/step - loss: 0.0016 - accuracy: 0.9996 - val_loss: 0.6451 - val_accuracy: 0.9064
Epoch 6/10
215/215 [==============================] - 12s 56ms/step - loss: 5.2044e-04 - accuracy: 0.9999 - val_loss: 0.7009 - val_accuracy: 0.9070
Epoch 7/10
215/215 [==============================] - 12s 57ms/step - loss: 3.5035e-04 - accuracy: 0.9999 - val_loss: 0.7206 - val_a

#### The final validation accuracy that we got is 90.73%

## Adding Dropout

In [32]:
from tensorflow.keras.layers import Dropout
embedding_vector_features = 40 
model1 = Sequential()
model1.add(Embedding(vocab_size, embedding_vector_features, input_length=sent_length))
model1.add(Dropout(0.3)) 
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3)) 
model1.add(Dense(1, activation = "sigmoid"))
model1.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 40)            200000    
_________________________________________________________________
dropout (Dropout)            (None, 25, 40)            0         
_________________________________________________________________
bidirectional_1 (Bidirection (None, 200)               112800    
_________________________________________________________________
dropout_1 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [33]:
model1.fit(X_train, y_train, validation_data =(X_test, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
215/215 [==============================] - 12s 58ms/step - loss: 0.3273 - accuracy: 0.8418 - val_loss: 0.2097 - val_accuracy: 0.9053
Epoch 2/10
215/215 [==============================] - 12s 55ms/step - loss: 0.1500 - accuracy: 0.9408 - val_loss: 0.1908 - val_accuracy: 0.9160
Epoch 3/10
215/215 [==============================] - 12s 55ms/step - loss: 0.1124 - accuracy: 0.9562 - val_loss: 0.2253 - val_accuracy: 0.9169
Epoch 4/10
215/215 [==============================] - 12s 55ms/step - loss: 0.0835 - accuracy: 0.9688 - val_loss: 0.2366 - val_accuracy: 0.9167
Epoch 5/10
215/215 [==============================] - 12s 55ms/step - loss: 0.0567 - accuracy: 0.9792 - val_loss: 0.2780 - val_accuracy: 0.9134
Epoch 6/10
215/215 [==============================] - 13s 58ms/step - loss: 0.0407 - accuracy: 0.9860 - val_loss: 0.2978 - val_accuracy: 0.9160
Epoch 7/10
215/215 [==============================] - 12s 58ms/step - loss: 0.0286 - accuracy: 0.9903 - val_loss: 0.3458 - val_accuracy:

#### Even after adding dropout layers, the accuracy remains the same i.e. 90.73%

## Performance Metrics And Accuracy

In [34]:
y_pred = model.predict(X_test) # Without Dropout
y_pred1 = model1.predict(X_test) # With Dropout

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
#Without Dropout
confusion_matrix(y_test, y_pred.round())

array([[2335,  265],
       [ 157, 1815]])

In [37]:
#With Dropout
confusion_matrix(y_test, y_pred1.round())

array([[2370,  230],
       [ 183, 1789]])

In [38]:
#Without Dropout
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred.round())

0.9076990376202975

In [39]:
#With Dropout
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred1.round())

0.9096675415573053

## Precision, Recall and F1 Score

In [40]:
#Without Dropout
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred.round()))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92      2600
           1       0.87      0.92      0.90      1972

    accuracy                           0.91      4572
   macro avg       0.90      0.91      0.91      4572
weighted avg       0.91      0.91      0.91      4572



In [41]:
#With Dropout
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred1.round()))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      2600
           1       0.89      0.91      0.90      1972

    accuracy                           0.91      4572
   macro avg       0.91      0.91      0.91      4572
weighted avg       0.91      0.91      0.91      4572

